export interface NetworkGym {
  id: string;
  name: string;
  address: string;
  city?: string;
  rating: number;
  distance: number;
  cost: number;
  slots: number;
  image: string;
  logo?: string;
  tags: string[];
  type: string;
  isPremium?: boolean;
  isBeginnerFriendly?: boolean;
  isBestValue?: boolean;
  isNearPrimary?: boolean;
  isVerified?: boolean;
  reviewCount?: number;
  ambience?: boolean;
  rank?: number;
  policies?: string[];
}

export const DEFAULT_GYM_POLICIES: string[] = [
  "Proper athletic workout attire & clean training shoes are mandatory.",
  "Please carry a personal workout towel and a refillable water bottle.",
  "Arrive 5–10 minutes prior to your reserved time slot.",
  "Always re-rack weights and wipe down equipment after use.",
  "Show your ZonoFit booking confirmation at reception for check-in.",
];

export const CANCELLATION_POLICY_NOTE = 
  "Cancel 6+ hours before your booking for full credit refund. Late cancellations may not be refundable.";

export interface PartnerCity {
  id: string;
  name: string;
  state: string;
  centresCount: number;
  isRestrictedHomeCity?: boolean;
  image: string;
  tagline: string;
}

export const PARTNER_CITIES: PartnerCity[] = [
  {
    id: "city-delhi",
    name: "Delhi NCR",
    state: "Delhi & NCR",
    centresCount: 15,
    tagline: "Connaught Place, Gurgaon, Noida",
    image: "https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "city-mumbai",
    name: "Mumbai",
    state: "Maharashtra",
    centresCount: 12,
    tagline: "Bandra, Andheri, Juhu, BKC",
    image: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "city-bengaluru",
    name: "Bengaluru",
    state: "Karnataka",
    centresCount: 14,
    tagline: "Indiranagar, Koramangala, HSR",
    image: "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "city-jaipur",
    name: "Jaipur",
    state: "Rajasthan",
    centresCount: 8,
    tagline: "Malviya Nagar, Mansarovar, C-Scheme",
    image: "https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "city-udaipur",
    name: "Udaipur",
    state: "Rajasthan",
    centresCount: 10,
    isRestrictedHomeCity: true,
    tagline: "Home City • 🔒 Primary Gym Restricted",
    image: "https://images.unsplash.com/photo-1615836245337-f5b9b2303f10?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "city-ahmedabad",
    name: "Ahmedabad",
    state: "Gujarat",
    centresCount: 6,
    tagline: "SG Highway, Bodakdev, Prahlad Nagar",
    image: "https://images.unsplash.com/photo-1609137144813-7d9921338f24?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "city-pune",
    name: "Pune",
    state: "Maharashtra",
    centresCount: 8,
    tagline: "Koregaon Park, Kothrud, Baner",
    image: "https://images.unsplash.com/photo-1625244724120-1fd1d34d00f6?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "city-indore",
    name: "Indore",
    state: "Madhya Pradesh",
    centresCount: 5,
    tagline: "Vijay Nagar, Palasia, AB Road",
    image: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&q=80&w=600",
  },
];

export const FALLBACK_NETWORK_GYMS: NetworkGym[] = [
  // ─── UDAIPUR GYMS (Home City Restricted) ───
  {
    id: "gym-friends-fitness",
    name: "Friends Fitness Zone",
    address: "Jawahar Nagar, Udaipur",
    city: "Udaipur",
    rating: 4.8,
    distance: 1.42,
    cost: 8,
    slots: 20,
    image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=600",
    logo: "https://images.unsplash.com/photo-1574680096145-d05b474e2155?auto=format&fit=crop&q=80&w=120",
    tags: ["Strength", "Cardio", "Lockers"],
    type: "gym",
    isVerified: true,
    reviewCount: 50,
    policies: [
      "Clean athletic footwear is strictly required inside the workout zone.",
      "Personal workout towel is mandatory for all machines & benches.",
      "Present your active ZonoFit booking ID at the reception desk.",
      "Please re-rack all free weights and dumbbells after your set."
    ],
  },
  {
    id: "gym-healthline-studio",
    name: "Healthline Fitness Studio",
    address: "Panchwati, Udaipur",
    city: "Udaipur",
    rating: 4.8,
    distance: 1.85,
    cost: 8,
    slots: 18,
    image: "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&q=80&w=600",
    logo: "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?auto=format&fit=crop&q=80&w=120",
    tags: ["CrossFit", "Cardio", "Steam"],
    type: "gym",
    isVerified: true,
    reviewCount: 50,
    ambience: true,
    policies: [
      "Appropriate sportswear and indoor training shoes required.",
      "Steam bath access requires a mandatory shower prior to entry.",
      "CrossFit rig equipment must be reset after workout.",
      "Arrive 5–10 minutes before your slot timing."
    ],
  },
  {
    id: "gym-b1-fitness",
    name: "81 Fitness Zone",
    address: "Malla Tala, Udaipur",
    city: "Udaipur",
    rating: 5.0,
    distance: 1.34,
    cost: 8,
    slots: 22,
    image: "https://images.unsplash.com/photo-1576678927484-cc907957088c?auto=format&fit=crop&q=80&w=600",
    logo: "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&q=80&w=120",
    tags: ["Treadmills", "Strength", "AC"],
    type: "gym",
    isVerified: true,
    reviewCount: 1,
    policies: [
      "Mandatory clean training shoes (outdoor muddy shoes not permitted).",
      "Treadmill sessions capped at 30 minutes during peak hours.",
      "Carry personal water bottle and gym towel.",
      "Show booking pass upon entering."
    ],
  },
  {
    id: "gym-the-fitness-zone",
    name: "The Fitness Zone",
    address: "Ashok Nagar, Udaipur",
    city: "Udaipur",
    rating: 4.9,
    distance: 1.37,
    cost: 8,
    slots: 16,
    image: "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?auto=format&fit=crop&q=80&w=600",
    logo: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=120",
    tags: ["Strength", "Zumba", "Trainers"],
    type: "gym",
    isVerified: true,
    reviewCount: 48,
    ambience: true,
    policies: [
      "Full gym attire and clean rubber-sole shoes required.",
      "Zumba studio requires dedicated indoor footwear.",
      "Wipe down cardio machines after use.",
      "Follow trainer guidance for safety on heavy lifts."
    ],
  },
  {
    id: "gym-kakes-gym",
    name: "Kakes Gym",
    address: "Bhuwana, Udaipur",
    city: "Udaipur",
    rating: 4.7,
    distance: 1.54,
    cost: 8,
    slots: 25,
    image: "https://images.unsplash.com/photo-1571902943202-507ec2618e8f?auto=format&fit=crop&q=80&w=600",
    logo: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&q=80&w=120",
    tags: ["Heavy Weights", "CrossFit"],
    type: "gym",
    isVerified: true,
    reviewCount: 12,
    policies: [
      "Weight lifting chalk permitted only at deadlift platforms.",
      "Drop weights only onto rubberized drop pads.",
      "Clean training sneakers required at all times.",
      "Respect gym equipment and fellow members."
    ],
  },
  {
    id: "gym-arnold-fitness",
    name: "Rnold Fitness Club",
    address: "Sector 11, Udaipur",
    city: "Udaipur",
    rating: 3.9,
    distance: 2.43,
    cost: 6,
    slots: 30,
    image: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&q=80&w=600",
    logo: "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&q=80&w=120",
    tags: ["Dumbbells", "Cardio", "Lockers"],
    type: "gym",
    isVerified: true,
    reviewCount: 3,
    policies: [
      "Wear appropriate sportswear and shoes.",
      "Lockers available for personal belongings — bring a small padlock.",
      "Keep phone on silent or vibrate in workout areas.",
      "Show ZonoFit visit pass at entrance."
    ],
  },
  {
    id: "gym-fitness-freak",
    name: "The Fitness Freak Health Club Gym",
    address: "Fatehpura, Udaipur",
    city: "Udaipur",
    rating: 4.0,
    distance: 2.52,
    cost: 7,
    slots: 19,
    image: "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&q=80&w=600",
    logo: "https://images.unsplash.com/photo-1576678927484-cc907957088c?auto=format&fit=crop&q=80&w=120",
    tags: ["Gym", "Aerobics", "Steam"],
    type: "gym",
    isVerified: true,
    reviewCount: 15,
    policies: [
      "Clean indoor gym shoes mandatory.",
      "Aerobics hall schedule must be adhered to.",
      "Steam bath open during specific morning & evening slots.",
      "Wipe down equipment after exercise."
    ],
  },
  {
    id: "gym-pranik-yoga",
    name: "Pranik Yoga Classes",
    address: "Rao Ji Ka Hata, Udaipur",
    city: "Udaipur",
    rating: 5.0,
    distance: 2.10,
    cost: 6,
    slots: 15,
    image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&q=80&w=600",
    logo: "https://images.unsplash.com/photo-1574680096145-d05b474e2155?auto=format&fit=crop&q=80&w=120",
    tags: ["Yoga", "Meditation", "Pilates"],
    type: "sports",
    isVerified: true,
    reviewCount: 1,
    rank: 1,
    policies: [
      "Remove footwear outside the yoga sanctuary.",
      "Bring personal yoga mat or sanitize studio mats after practice.",
      "Maintain peaceful atmosphere and silence inside hall.",
      "Arrive at least 5 minutes before meditation sessions begin."
    ],
  },
  {
    id: "gym-being-fit",
    name: "Being Fit Fitness",
    address: "Rao Ji Ka Hata, Udaipur",
    city: "Udaipur",
    rating: 5.0,
    distance: 2.20,
    cost: 8,
    slots: 20,
    image: "https://images.unsplash.com/photo-1593079831268-3381b0db4a77?auto=format&fit=crop&q=80&w=600",
    logo: "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?auto=format&fit=crop&q=80&w=120",
    tags: ["Strength", "Cardio", "CrossFit"],
    type: "gym",
    isVerified: true,
    reviewCount: 7,
    rank: 2,
    policies: [
      "Clean athletic footwear & gym apparel mandatory.",
      "Personal workout towel required for equipment contact.",
      "Re-rack dumbbells and barbells into rack slots.",
      "Check-in at front desk with ZonoFit booking pass."
    ],
  },
  {
    id: "gym-fitzone-pro",
    name: "FitZone Pro",
    address: "Sukher, Udaipur",
    city: "Udaipur",
    rating: 4.8,
    distance: 0.8,
    cost: 8,
    slots: 18,
    image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=600",
    logo: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=120",
    tags: ["Strength", "Cardio", "CrossFit", "AC"],
    type: "gym",
    isVerified: true,
    reviewCount: 112,
    rank: 3,
    policies: [
      "Proper gym shoes and clothing compulsory.",
      "Sanitize equipment after every use.",
      "Follow trainer guidance for safe lifting."
    ],
  },

  // ─── DELHI NCR GYMS (Bookable with Credits) ───
  {
    id: "gym-iron-paradise-delhi",
    name: "Iron Paradise Fitness Club",
    address: "Connaught Place, Central Delhi",
    city: "Delhi NCR",
    rating: 4.9,
    distance: 1.2,
    cost: 8,
    slots: 24,
    image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=600",
    logo: "https://images.unsplash.com/photo-1574680096145-d05b474e2155?auto=format&fit=crop&q=80&w=120",
    tags: ["Heavy Lifting", "Steam & Sauna", "Strength"],
    type: "gym",
    isVerified: true,
    reviewCount: 88,
    ambience: true,
  },
  {
    id: "gym-cult-gurgaon",
    name: "Cult.fit Sector 29 Cyber Hub",
    address: "Sector 29, Gurgaon",
    city: "Delhi NCR",
    rating: 4.8,
    distance: 2.4,
    cost: 8,
    slots: 18,
    image: "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&q=80&w=600",
    logo: "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?auto=format&fit=crop&q=80&w=120",
    tags: ["CrossFit", "HIIT", "Strength"],
    type: "gym",
    isVerified: true,
    reviewCount: 156,
  },
  {
    id: "gym-boxfit-noida",
    name: "BoxFit Arena & Combat Gym",
    address: "Sector 18, Noida",
    city: "Delhi NCR",
    rating: 4.7,
    distance: 3.1,
    cost: 10,
    slots: 15,
    image: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&q=80&w=600",
    tags: ["Boxing", "MMA Ring", "Cardio"],
    type: "sports",
    isVerified: true,
    reviewCount: 42,
  },
  {
    id: "gym-ozone-southdelhi",
    name: "Ozone Luxury Fitness",
    address: "Defence Colony, South Delhi",
    city: "Delhi NCR",
    rating: 4.9,
    distance: 3.8,
    cost: 10,
    slots: 12,
    image: "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?auto=format&fit=crop&q=80&w=600",
    tags: ["Luxury", "Steam Room", "Valet Parking"],
    type: "gym",
    isPremium: true,
    isVerified: true,
    reviewCount: 94,
    ambience: true,
  },
  {
    id: "gym-anytime-saket",
    name: "Anytime Fitness Saket",
    address: "Saket Community Centre, New Delhi",
    city: "Delhi NCR",
    rating: 4.6,
    distance: 4.5,
    cost: 7,
    slots: 20,
    image: "https://images.unsplash.com/photo-1576678927484-cc907957088c?auto=format&fit=crop&q=80&w=600",
    tags: ["24/7 Access", "Cardio", "Lockers"],
    type: "gym",
    isVerified: true,
    reviewCount: 65,
  },

  // ─── MUMBAI GYMS (Bookable with Credits) ───
  {
    id: "gym-crossfit-versova",
    name: "CrossFit Arena Mumbai",
    address: "Juhu Tara Road, Mumbai",
    city: "Mumbai",
    rating: 4.6,
    distance: 1.8,
    cost: 10,
    slots: 12,
    image: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&q=80&w=600",
    logo: "https://images.unsplash.com/photo-1574680096145-d05b474e2155?auto=format&fit=crop&q=80&w=120",
    tags: ["CrossFit", "HIIT", "Strength", "Outdoor Turf"],
    type: "turf",
    isVerified: true,
    reviewCount: 88,
  },
  {
    id: "gym-golds-bandra",
    name: "Gold's Gym Bandra West",
    address: "Pali Hill, Bandra West, Mumbai",
    city: "Mumbai",
    rating: 4.9,
    distance: 2.3,
    cost: 8,
    slots: 22,
    image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=600",
    logo: "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?auto=format&fit=crop&q=80&w=120",
    tags: ["Strength", "Celebrity Trainers", "Steam"],
    type: "gym",
    isPremium: true,
    isVerified: true,
    reviewCount: 210,
    ambience: true,
  },
  {
    id: "gym-powerhouse-andheri",
    name: "PowerHouse Elite Fitness",
    address: "Lokhandwala, Andheri West, Mumbai",
    city: "Mumbai",
    rating: 4.8,
    distance: 3.1,
    cost: 8,
    slots: 16,
    image: "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&q=80&w=600",
    tags: ["Performance Training", "Free Weights", "Cardio"],
    type: "gym",
    isVerified: true,
    reviewCount: 95,
  },
  {
    id: "gym-bkc-fitness-lounge",
    name: "BKC Fitness Lounge & Spa",
    address: "Bandra Kurla Complex, Mumbai",
    city: "Mumbai",
    rating: 4.9,
    distance: 4.2,
    cost: 12,
    slots: 14,
    image: "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?auto=format&fit=crop&q=80&w=600",
    tags: ["Executive", "Recovery Zone", "Steam & Jacuzzi"],
    type: "gym",
    isPremium: true,
    isVerified: true,
    reviewCount: 130,
    ambience: true,
  },
  {
    id: "gym-nitro-thane",
    name: "Nitro Fitness World",
    address: "Ghodbunder Road, Thane West",
    city: "Mumbai",
    rating: 4.7,
    distance: 6.5,
    cost: 7,
    slots: 25,
    image: "https://images.unsplash.com/photo-1576678927484-cc907957088c?auto=format&fit=crop&q=80&w=600",
    tags: ["Olympic Weights", "Zumba", "Shower"],
    type: "gym",
    isVerified: true,
    reviewCount: 76,
  },

  // ─── BENGALURU GYMS (Bookable with Credits) ───
  {
    id: "gym-zenith-turf",
    name: "Zenith Sports & Box Cricket",
    address: "HSR Layout Sector 2, Bengaluru",
    city: "Bengaluru",
    rating: 4.9,
    distance: 1.4,
    cost: 14,
    slots: 8,
    image: "https://images.unsplash.com/photo-1529900748604-07564a03e7a6?auto=format&fit=crop&q=80&w=600",
    tags: ["Turf", "Box Cricket", "Football", "Floodlights"],
    type: "turf",
    isPremium: true,
    isVerified: true,
    reviewCount: 65,
  },
  {
    id: "gym-cult-indiranagar",
    name: "Cult Fitness Center",
    address: "100 Feet Rd, Indiranagar, Bengaluru",
    city: "Bengaluru",
    rating: 4.8,
    distance: 1.8,
    cost: 8,
    slots: 20,
    image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=600",
    tags: ["HIIT", "Strength", "Cardio", "Locker Room"],
    type: "gym",
    isVerified: true,
    reviewCount: 142,
  },
  {
    id: "gym-anytime-fitness",
    name: "Anytime Fitness Koramangala",
    address: "Koramangala 5th Block, Bengaluru",
    city: "Bengaluru",
    rating: 4.7,
    distance: 2.3,
    cost: 7,
    slots: 15,
    image: "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?auto=format&fit=crop&q=80&w=600",
    tags: ["24/7 Access", "Cardio", "Lockers", "Shower"],
    type: "gym",
    isVerified: true,
    reviewCount: 98,
  },
  {
    id: "gym-olympus-strength",
    name: "Olympus Strength & Conditioning",
    address: "HSR Sector 1, Bengaluru",
    city: "Bengaluru",
    rating: 4.9,
    distance: 3.4,
    cost: 10,
    slots: 10,
    image: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?auto=format&fit=crop&q=80&w=600",
    tags: ["Olympic Lifting", "Powerlifting", "Turf", "AC"],
    type: "gym",
    isPremium: true,
    isVerified: true,
    reviewCount: 52,
  },
  {
    id: "gym-chisel-fitness",
    name: "Chisel Fitness Studio",
    address: "Richmond Town, Bengaluru",
    city: "Bengaluru",
    rating: 4.6,
    distance: 3.8,
    cost: 6,
    slots: 18,
    image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&q=80&w=600",
    tags: ["Cardio", "Steam", "Personal Trainer", "Parking"],
    type: "gym",
    isVerified: true,
    reviewCount: 40,
  },

  // ─── JAIPUR GYMS (Bookable with Credits) ───
  {
    id: "gym-golds-jaipur",
    name: "Gold's Gym Malviya Nagar",
    address: "Malviya Nagar, Jaipur",
    city: "Jaipur",
    rating: 4.8,
    distance: 1.5,
    cost: 8,
    slots: 20,
    image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=600",
    tags: ["Cardio", "Strength", "Steam"],
    type: "gym",
    isVerified: true,
    reviewCount: 78,
  },
  {
    id: "gym-fit7-jaipur",
    name: "Fit7 by MS Dhoni",
    address: "Mansarovar, Jaipur",
    city: "Jaipur",
    rating: 4.9,
    distance: 2.1,
    cost: 8,
    slots: 18,
    image: "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&q=80&w=600",
    tags: ["CrossFit", "Zumba", "AC"],
    type: "gym",
    isVerified: true,
    reviewCount: 65,
    ambience: true,
  },
  {
    id: "gym-anytime-c-scheme",
    name: "Anytime Fitness C-Scheme",
    address: "C-Scheme, Ashok Nagar, Jaipur",
    city: "Jaipur",
    rating: 4.7,
    distance: 2.8,
    cost: 7,
    slots: 22,
    image: "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?auto=format&fit=crop&q=80&w=600",
    tags: ["24/7 Access", "Treadmills", "Trainers"],
    type: "gym",
    isVerified: true,
    reviewCount: 44,
  },
  {
    id: "gym-titan-fitness-jaipur",
    name: "Titan Strength Arena",
    address: "Raja Park, Jaipur",
    city: "Jaipur",
    rating: 4.6,
    distance: 3.5,
    cost: 6,
    slots: 25,
    image: "https://images.unsplash.com/photo-1571902943202-507ec2618e8f?auto=format&fit=crop&q=80&w=600",
    tags: ["Heavy Weights", "Cardio", "Lockers"],
    type: "gym",
    isVerified: true,
    reviewCount: 30,
  },
  {
    id: "gym-energy-zone-jaipur",
    name: "Energy Zone Health Club",
    address: "Vaishali Nagar, Jaipur",
    city: "Jaipur",
    rating: 4.5,
    distance: 4.2,
    cost: 6,
    slots: 20,
    image: "https://images.unsplash.com/photo-1576678927484-cc907957088c?auto=format&fit=crop&q=80&w=600",
    tags: ["Strength", "Aerobics", "Steam"],
    type: "gym",
    isVerified: true,
    reviewCount: 22,
  },
];

export function getGymPolicies(gymIdOrName?: string | null): string[] {
  if (!gymIdOrName) return DEFAULT_GYM_POLICIES;
  const lower = gymIdOrName.toLowerCase();
  const match = FALLBACK_NETWORK_GYMS.find(
    (g) => g.id.toLowerCase() === lower || g.name.toLowerCase() === lower || g.name.toLowerCase().includes(lower) || lower.includes(g.name.toLowerCase())
  );
  if (match && match.policies && match.policies.length > 0) {
    return match.policies;
  }
  return DEFAULT_GYM_POLICIES;
}
